name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    permissions:
      contents: write

    strategy:
      max-parallel: 6
      matrix:
        build_configuration: [Release, Debug]
        build_platform: [x64, Win32, ARM64]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v7

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v3

    - name: MSBuild of plugin dll
      working-directory: vs.proj\
      run: msbuild HiddenLexers.vcxproj /m /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"

    - name: Archive artifacts for x64
      if: matrix.build_platform == 'x64' && matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v7
      with:
          name: plugin_dll_x64
          path: bin64\HiddenLexers.dll

    - name: Archive artifacts for Win32
      if: matrix.build_platform == 'Win32' && matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v7
      with:
          name: plugin_dll_x86
          path: bin\HiddenLexers.dll

    - name: Archive artifacts for ARM64
      if: matrix.build_platform == 'ARM64' && matrix.build_configuration == 'Release'
      uses: actions/upload-artifact@v7
      with:
          name: plugin_dll_arm64
          path: arm64\HiddenLexers.dll

    - name: Create ${{ matrix.build_platform }} Release zipfile
      if: startsWith(github.ref, 'refs/tags/v') && matrix.build_configuration == 'Release'
      working-directory: .
      run: |
        echo "This only runs on a tag, I hope"
        if(!(Test-Path -Path .\doc)) {
            New-Item -ItemType Directory -Path .\doc
        }
        Copy-Item -Path README.md -Destination .\doc\
        Copy-Item -Path license.txt -Destination .\doc\
        if((Test-Path -Path bin64\HiddenLexers.dll)) {
            Copy-Item -Path bin64\HiddenLexers.dll -Destination .\HiddenLexers.dll
        }
        if((Test-Path -Path bin\HiddenLexers.dll)) {
            Copy-Item -Path bin\HiddenLexers.dll -Destination .\HiddenLexers.dll
        }
        if((Test-Path -Path arm64\HiddenLexers.dll)) {
            Copy-Item -Path arm64\HiddenLexers.dll -Destination .\HiddenLexers.dll
        }
        $zipName = "HiddenLexers_${{ github.ref_name }}_${{ matrix.build_platform }}.zip"
        $filesToZip = "HiddenLexers.dll", ".\doc\"
        Compress-Archive -Path $filesToZip -Destination $zipName
        dir
    - name: 🎉 Store ${{ matrix.build_platform }} zipfile as asset
      if: startsWith(github.ref, 'refs/tags/v') && matrix.build_configuration == 'Release'
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./HiddenLexers_${{ github.ref_name }}_${{ matrix.build_platform }}.zip
        asset_name: HiddenLexers_${{ github.ref_name }}_${{ matrix.build_platform }}.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: ${{ github.event.release.body }}
